/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DisasterSensorEnterprise.FloodManagement;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FloodManagementOrganization;
import Business.Organization.SensorMonitorOrganization;
import Business.Organization.GovernmentOfficialOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Sensor.FloodSensor;
import Business.Sensor.Sensor;
import Business.Sensor.SensorDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FloodWorkRequest;
import Business.WorkQueue.GovernmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import UI.DisasterSensorEnterprise.SensorManagement.SensorMonitorWorkArea;

/**
 *
 * @author moins
 */
public class NotifyToGovernmentJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private OrganizationDirectory organizationDirectory;
    

    /**
     * Creates new form NotifyToGovernmentJPanel
     */
    public NotifyToGovernmentJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem business, OrganizationDirectory organizationDirectory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        this.organizationDirectory = organizationDirectory;
        
        populateTable();
    }
    
    public void populateTable(){
         ArrayList<FloodSensor> tempFloodSensorList = new ArrayList<FloodSensor>();

        for(Network ntwk: business.getNetworkList())
        {
            for(Enterprise entprise : ntwk.getEnterpriseDirectory().getEnterpriseList())
            {
                for(Organization org : entprise.getOrganizationDirectory().getOrganizationList())
            {
            if(org instanceof SensorMonitorOrganization)
            {
                SensorDirectory sensedirect;
                sensedirect = ((SensorMonitorOrganization) org).getSensorDirectory();
                
                for(Sensor sense : sensedirect.getSensorList())
                {
                    if(sense instanceof FloodSensor)
                    {
                        FloodSensor air = (FloodSensor)sense;
                        tempFloodSensorList.add(air);
                    }
                }
            }

            }
        }   }
            
            DefaultTableModel model = (DefaultTableModel) tblFlood.getModel();
        model.setRowCount(0);
        
        for(FloodSensor css : tempFloodSensorList)
                {
                    if(css.getCurrentlevel()>200)
                    {
                        Object[] row = new Object[4];
                        row[0] = css;
                        row[1] = css.getZipcode();
                        row[2] = css.getCurrentlevel();
                        model.addRow(row);
                    }
                }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlood = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRequestToGovernment = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 222, 248));
        setLayout(null);

        tblFlood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sensor ID", "Zipcode", "Water Level"
            }
        ));
        jScrollPane1.setViewportView(tblFlood);

        add(jScrollPane1);
        jScrollPane1.setBounds(190, 300, 700, 190);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(91, 130, 170));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flood Sensor Readings");
        add(jLabel1);
        jLabel1.setBounds(270, 130, 540, 60);

        btnBack.setText("<< Back");
        btnBack.setSize(new java.awt.Dimension(120, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 20, 80, 50);

        btnRequestToGovernment.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnRequestToGovernment.setText("Send Request To Government");
        btnRequestToGovernment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestToGovernmentActionPerformed(evt);
            }
        });
        add(btnRequestToGovernment);
        btnRequestToGovernment.setBounds(390, 530, 330, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/flood-read-1.jpeg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(-60, 190, 1160, 670);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestToGovernmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestToGovernmentActionPerformed
        // TODO add your handling code here:
        int row = tblFlood.getSelectedRow();
        if(row <0){
            JOptionPane.showMessageDialog(null, "No row selected");
        }else{
        //AirPollutionSensor airPollutionSensor = (AirPollutionSensor)SensorReadingsjTable.getValueAt(row, 0);
        
        Sensor sensor = (Sensor)tblFlood.getValueAt(row, 0);
        
        FloodSensor floodSensor = (FloodSensor) sensor;
        GovernmentWorkRequest reques = new GovernmentWorkRequest();
        reques.setFloodSensor(floodSensor);
        reques.setFloodMessage("Area-code "+floodSensor.getZipcode()+" is flooded, please inform citizens to avoid this area until further notice");
        reques.setSender(userAccount);
        reques.setStatus("Successfully Notified to Government");
        
        Organization orgn = null;
        for(Network ntwk: business.getNetworkList())
        {
            for(Enterprise enterprise : ntwk.getEnterpriseDirectory().getEnterpriseList())
            {
                for(Organization orgzn : enterprise.getOrganizationDirectory().getOrganizationList())
                {
 
            if (orgzn instanceof GovernmentOfficialOrganization){
                orgn = orgzn;
                break;
                    }           
                }
            } 
        }
        if (orgn!=null){
            
            ArrayList<Integer> sensorIDsArray = new ArrayList<Integer>();
            boolean workRequestAlreadyPresent = false;
                    
            if(orgn.getWorkQueue().getWorkRequestList().isEmpty())
            {
                try {
                 orgn.getWorkQueue().getWorkRequestList().add(reques);
                userAccount.getWorkQ().getWorkRequestList().add(reques);
                JOptionPane.showMessageDialog(null, "Request sent to Government successfully");
                return;
                } catch (Exception e) {
                }
                JOptionPane.showMessageDialog(null, "Request sent to Government successfully");
            }
            else
            {
            for(WorkRequest request1 : orgn.getWorkQueue().getWorkRequestList())
            {
                if(request1 instanceof GovernmentWorkRequest)
                {
                    GovernmentWorkRequest reque = (GovernmentWorkRequest) request1;
                    
                    if(reque.getFloodSensor() != null)
                    {
                    sensorIDsArray.add(reque.getFloodSensor().getSensorId());
                    for(int i=0; i<sensorIDsArray.size(); i++)
                    {
                        if(reques.getFloodSensor().getSensorId() == sensorIDsArray.get(i))
                        {
                            workRequestAlreadyPresent = true;
                        }
                    }
                  }
                }
              }
                    if(workRequestAlreadyPresent)   
                    {
                        JOptionPane.showMessageDialog(null, "Request has already been sent to Government");
                    }
                    else
                    {
                        try {
                        orgn.getWorkQueue().getWorkRequestList().add(reques);
                        userAccount.getWorkQ().getWorkRequestList().add(reques);
                        JOptionPane.showMessageDialog(null, "Request sent to Government successfully");
                        return;
                        } catch (Exception e) {
                        }
                        JOptionPane.showMessageDialog(null, "Request sent to Government successfully");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRequestToGovernmentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);  
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
 
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestToGovernment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFlood;
    // End of variables declaration//GEN-END:variables
}
