/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.DisasterManagementAdminRole;
import Business.Role.SensorManagementAdminRole;
import Business.Role.GovernmentAgencyAdminRole;
import Business.Role.RNDAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moins
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    public static int selectedRowIndex = -1;
    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateCityComboBox();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_Admin.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
            }
        }
    }
    
    private void populateCityComboBox() {
        combo_city.removeAllItems();

        for (Network network : system.getNetworkList()) {
            combo_city.addItem(network);
        }
    }

    private void populateEnterpriseComboBox(Network network) {
        Combo_enterprise.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            Combo_enterprise.addItem(enterprise);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combo_city = new javax.swing.JComboBox();
        Combo_enterprise = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Admin = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        txt_submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 222, 248));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("City");
        add(jLabel1);
        jLabel1.setBounds(120, 340, 130, 21);

        combo_city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_city.setForeground(new java.awt.Color(0, 0, 51));
        combo_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_cityActionPerformed(evt);
            }
        });
        add(combo_city);
        combo_city.setBounds(330, 330, 227, 30);

        Combo_enterprise.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Combo_enterprise.setForeground(new java.awt.Color(0, 0, 51));
        Combo_enterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_enterpriseActionPerformed(evt);
            }
        });
        add(Combo_enterprise);
        Combo_enterprise.setBounds(330, 400, 227, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Enterprise");
        add(jLabel3);
        jLabel3.setBounds(120, 400, 150, 21);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        add(jLabel2);
        jLabel2.setBounds(120, 540, 140, 21);

        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 0, 51));
        add(txtUsername);
        txtUsername.setBounds(330, 530, 227, 30);

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 51));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword);
        txtPassword.setBounds(330, 600, 227, 30);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        add(jLabel4);
        jLabel4.setBounds(120, 600, 130, 21);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Name");
        add(jLabel5);
        jLabel5.setBounds(120, 470, 130, 21);

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 0, 51));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(330, 460, 227, 30);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setText("Manage Enterprise Admin");
        add(jLabel6);
        jLabel6.setBounds(230, 100, 340, 29);

        tbl_Admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterperise", "Network", "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_Admin);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 160, 720, 140);

        btn_back.setText("<<Back");
        btn_back.setPreferredSize(new java.awt.Dimension(120, 40));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(20, 10, 95, 50);

        txt_submit.setText("Submit");
        txt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_submitActionPerformed(evt);
            }
        });
        add(txt_submit);
        txt_submit.setBounds(380, 690, 120, 40);

        jLabel7.setBackground(new java.awt.Color(222, 222, 248));
        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, -60, 1870, 1010);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_cityActionPerformed

        Network network = (Network) combo_city.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_combo_cityActionPerformed

    private void Combo_enterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_enterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_enterpriseActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
     userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_submitActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String pss = txtPassword.getText();
        String user =txtUsername.getText();
        
        if(name.isEmpty() || pss.isEmpty() || user.isEmpty()){
         JOptionPane.showMessageDialog(null, "No field should be blank");
        }
        else{
        try {
            Enterprise enterprise = (Enterprise) Combo_enterprise.getSelectedItem();

            String username = txtUsername.getText();
            String password = String.valueOf(txtPassword.getPassword());
            
            Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
           
            if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.DisasterManagement) {
                if (system.UniqueUserName(username)) {
                    UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new DisasterManagementAdminRole());
                } else {
                    JOptionPane.showMessageDialog(null, "User name already exist");
                    return;
                }
            } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.GovernmentAgency) {
                if (system.UniqueUserName(username)) {
                    UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new GovernmentAgencyAdminRole());
                } else {
                    JOptionPane.showMessageDialog(null, "User name already exist");
                    return;
                }
            } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.SensorManagement) {
                if (system.UniqueUserName(username)) {
                    UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new SensorManagementAdminRole());
                } else {
                    JOptionPane.showMessageDialog(null, "User name already exist");
                    return;
                }
            } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.ResearchAndDevelopment) {
                if (system.UniqueUserName(username)) {
                    UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new RNDAdminRole());
                } else {
                    JOptionPane.showMessageDialog(null, "User name already exist");
                    return;
                }
            }    
            populateTable();
            JOptionPane.showMessageDialog(this, "Enterprise Admin Added");
            txtName.setText("");
            txtUsername.setText("");
            txtPassword.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something is wrong! You dont have an enterprise it seems");
        }
        }
    }//GEN-LAST:event_txt_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_enterprise;
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox combo_city;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_Admin;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JButton txt_submit;
    // End of variables declaration//GEN-END:variables
}
