/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DisasterManagementWorkQueue;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FloodManagementOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author moins
 */
public class FloodManagementWorkJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final UserAccount account;
    private final Enterprise enterprise;
    private final EcoSystem business;
    private final FloodManagementOrganization organization;

    /**
     * Creates new form FloodAlertManagementWorkAreaJPanel
     */
    public FloodManagementWorkJPanel(JPanel userProcessContainer, UserAccount account, FloodManagementOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnViewWorkQueue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 222, 248));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(91, 130, 170));
        lblTitle.setText("Flood Management Work Area");
        add(lblTitle);
        lblTitle.setBounds(240, 150, 760, 80);

        btnViewWorkQueue.setBackground(new java.awt.Color(91, 130, 170));
        btnViewWorkQueue.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnViewWorkQueue.setForeground(new java.awt.Color(255, 255, 255));
        btnViewWorkQueue.setText("View Work Queue");
        btnViewWorkQueue.setSize(new java.awt.Dimension(260, 70));
        btnViewWorkQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewWorkQueueActionPerformed(evt);
            }
        });
        add(btnViewWorkQueue);
        btnViewWorkQueue.setBounds(460, 530, 260, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Flood2.jpeg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 220, 1190, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewWorkQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewWorkQueueActionPerformed
        // TODO add your handling code here:
        FloodManagementWorkQueueJPanel floodmanagementWorkQueue = new FloodManagementWorkQueueJPanel(userProcessContainer, account, enterprise.getOrganizationDirectory());        userProcessContainer.add("floodManagementWorkQueue", floodmanagementWorkQueue);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewWorkQueueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewWorkQueue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
